-- TABELAS
USE MASTER
GO
DROP DATABASE db_CARROS

SP_HELPDB db_CARROS

CREATE DATABASE db_CARRO
ON PRIMARY(
	NAME = db_CARRO,
	FILENAME = 'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\db_CARRO.mdf',
	SIZE=6MB,
	MAXSIZE=15MB,
	FILEGROWTH=10%
)
GO
USE db_CARRO


CREATE TABLE tb_CARRO(
	CAR_CODIGO		INT PRIMARY KEY IDENTITY(1,1),
	CAR_MARCA		VARCHAR(50) CONSTRAINT nn_CAR_MARCA NOT NULL,
	CAR_MODELO		VARCHAR(50) CONSTRAINT nn_CAR_MODELO NOT NULL,
	CAR_COR			VARCHAR(50) CONSTRAINT nn_CAR_COR NOT NULL,
	CAR_ANO			DATE CONSTRAINT nn_CAR_ANO NOT NULL,
	CAR_PRECO		MONEY CONSTRAINT nn_CAR_PRECO NOT NULL,
)



CREATE TABLE tb_OPCIONAL(
	OPC_CODIGO		INT PRIMARY KEY IDENTITY(1,1),
	OPC_DESCRICAO	VARCHAR(50)
)




CREATE TABLE tb_OPCIONAL_CARRO(
	FK_CAR_CODIGO	INT FOREIGN KEY REFERENCES tb_CARRO(CAR_CODIGO),
	FK_OPC_CODIGO	INT FOREIGN KEY REFERENCES tb_OPCIONAL(OPC_CODIGO),
	CONSTRAINT pk_CHAVE_COMPOSTA PRIMARY KEY(FK_CAR_CODIGO,FK_OPC_CODIGO)
)




CREATE TABLE tb_CLIENTE(
	CLI_CODIGO		INT PRIMARY KEY IDENTITY(1,1),
	CLI_NOME		VARCHAR(50) CONSTRAINT nn_CLI_NOME NOT NULL,
	CLI_CPF			VARCHAR(30) CONSTRAINT nn_CLI_NOME NOT NULL,
	CLI_SEXO		VARCHAR(30) CONSTRAINT chk_CLI_SEXO CHECK(CLI_SEXO IN('MASCULINO', 'FEMININO')) CONSTRAINT nn_CLI_SEXO NOT NULL,
	FK_CAR_CODIGO	INT FOREIGN KEY REFERENCES tb_CARRO(CAR_CODIGO)
)



CREATE TABLE tb_ENDERECO(
	END_CODIGO		INT PRIMARY KEY IDENTITY(1,1),
	END_RUA			VARCHAR(100) CONSTRAINT nn_END_RUA NOT NULL,
	END_BAIRRO		VARCHAR(100) CONSTRAINT nn_END_BAIRRO NOT NULL,
	END_CEP			VARCHAR(20) CONSTRAINT nn_END_CEP NOT NULL,
	END_COMPLEMENTO	VARCHAR(100) CONSTRAINT nn_END_COMPLEMENTO NOT NULL,
	FK_CLI_CODIGO	INT FOREIGN KEY REFERENCES tb_CLIENTE(CLI_CODIGO)
)



CREATE TABLE TELEFONE(
	TEL_CODIGO		INT PRIMARY KEY IDENTITY(1,1),
	FK_CLI_CODIGO	INT FOREIGN KEY REFERENCES tb_CLIENTE(CLI_CODIGO),
	TEL_TELEFONE	VARCHAR(50) CONSTRAINT nn_TEL_TELEFONE NOT NULL
)



CREATE TABLE tb_FINANCEIRO(
	FIN_CODIGO		INT PRIMARY KEY IDENTITY(1,1),
	FIN_VALOR		MONEY CONSTRAINT nn_FIN_VALOR NOT NULL,
	FIN_PARCELAS	INT CONSTRAINT chk_FIN_PARCELAS CHECK (FIN_PARCELAS IN(12,24,36,48,60)),
	FIN_PERCENTUAL	INT	CONSTRAINT chk_FIN_PERCENTUAL CHECK (FIN_PERCENTUAL IN(20,30,40,50)),
	FIN_VENCIMENTO	INT CONSTRAINT chk_FIN_VENCIMENTO CHECK (FIN_VENCIMENTO IN(5,10,15,20,25)),
	FK_CLI_CODIGO	INT FOREIGN KEY REFERENCES tb_CLIENTE(CLI_CODIGO)
)
