-- tb_ENDEREÇO


USE db_CARRO



-- CRIAR ENDERECO
IF EXISTS (SELECT * FROM SYS.objects WHERE OBJECT_ID = OBJECT_ID(N'SP_CRIAR_ENDERECO'))
	DROP PROCEDURE SP_CRIAR_ENDERECO
GO
CREATE PROCEDURE SP_CRIAR_ENDERECO

	@RUA			VARCHAR(100),
	@BAIRRO			VARCHAR(100),
	@CEP			VARCHAR(20),
	@COMPLEMENTO	VARCHAR(100),
	@ID_CLIENTE		INT 


AS
BEGIN

	INSERT tb_ENDERECO	(
							 END_RUA,			
							 END_BAIRRO,		
							 END_CEP,			
							 END_COMPLEMENTO,	
							 FK_CLI_CODIGO	
						)
	VALUES	(
				@RUA,
				@BAIRRO,		
				@CEP,		
				@COMPLEMENTO,
				@ID_CLIENTE	
			)
END




-- EDITAR ENDERECO
IF EXISTS (SELECT * FROM SYS.objects WHERE OBJECT_ID = OBJECT_ID(N'SP_EDITAR_ENDERECO'))
	DROP PROCEDURE SP_EDITAR_ENDERECO
GO
CREATE PROCEDURE SP_EDITAR_ENDERECO
	
	@ID				INT,
	@RUA			VARCHAR(100),
	@BAIRRO			VARCHAR(100),
	@CEP			VARCHAR(20),
	@COMPLEMENTO	VARCHAR(100)

AS
BEGIN

	UPDATE tb_ENDERECO SET
							 END_RUA = @RUA,			
							 END_BAIRRO = @BAIRRO,		
							 END_CEP = @CEP,			
							 END_COMPLEMENTO = @COMPLEMENTO						
	WHERE END_CODIGO = @ID

END











-- EXCLUIR ENDEREÇO
IF EXISTS (SELECT * FROM SYS.objects WHERE OBJECT_ID = OBJECT_ID(N'SP_EXCLUIR_ENDERECO'))
	DROP PROCEDURE SP_EXCLUIR_ENDERECO
GO
CREATE PROCEDURE SP_EXCLUIR_ENDERECO
	
	@ID				INT

AS
BEGIN
	
	DELETE FROM tb_ENDERECO WHERE FK_CLI_CODIGO = @ID

END
