-- TABELA OPCIONAL

USE db_CARRO


IF EXISTS (SELECT * FROM SYS.objects WHERE OBJECT_ID = OBJECT_ID(N'SP_CRIAR_OPCINAL'))
	DROP PROCEDURE SP_CRIAR_OPCINAL
GO
CREATE PROCEDURE SP_CRIAR_OPCINAL
	@IDCARRO		INT,
	@OPC_DESCRICAO	VARCHAR(50)

AS
BEGIN

	INSERT tb_OPCIONAL (
							OPC_DESCRICAO
						)
	VALUES (
				@OPC_DESCRICAO
			)
	
	RETURN SCOPE_IDENTITY()

END