-- TABELA tb_OPCIONAL_CARRO

USE db_CARRO
SELECT * FROM tb_OPCIONAL_CARRO





IF EXISTS (SELECT * FROM SYS.objects WHERE OBJECT_ID = OBJECT_ID(N'SP_CRIAR_OPCINAL_CARRO'))
	DROP PROCEDURE SP_CRIAR_OPCINAL_CARRO
GO
CREATE PROCEDURE SP_CRIAR_OPCINAL_CARRO
	@IDCARRO		INT,
	@IDOPCIONAL		INT

AS
BEGIN
	
	INSERT tb_OPCIONAL_CARRO (
								FK_CAR_CODIGO,
								FK_OPC_CODIGO
							 )
	VALUES(
				@IDCARRO,	
				@IDOPCIONAL
		  )
END
EXEC SP_CRIAR_OPCINAL_CARRO 31, 11









IF EXISTS (SELECT * FROM SYS.objects WHERE OBJECT_ID = OBJECT_ID(N'SP_DELETAR_OPCINAL_CARRO'))
	DROP PROCEDURE SP_DELETAR_OPCINAL_CARRO
GO
CREATE PROCEDURE SP_DELETAR_OPCINAL_CARRO
	@ID		INT

AS
BEGIN

		DELETE tb_OPCIONAL_CARRO WHERE FK_CAR_CODIGO = @ID

END
EXEC SP_DELETAR_OPCINAL_CARRO 31