-- TABELA CARRO

USE db_CARRO
SELECT * FROM tb_CARRO




-- CRIAR
IF EXISTS (SELECT * FROM SYS.objects WHERE OBJECT_ID = OBJECT_ID(N'SP_CRIAR_CARRO'))
	DROP PROCEDURE SP_CRIAR_CARRO
GO
CREATE PROCEDURE SP_CRIAR_CARRO
	@MARCA		VARCHAR(50),		
	@MODELO		VARCHAR(50),	
	@COR		VARCHAR(50),		
	@ANO		DATE,		
	@PRECO		MONEY
AS
BEGIN
	INSERT tb_CARRO (
						 CAR_MARCA,	
						 CAR_MODELO,	
						 CAR_COR,		
						 CAR_ANO,		
						 CAR_PRECO	
					 )
	VALUES	(
				@MARCA,	
				@MODELO,	
				@COR,		
				@ANO,		
				@PRECO							
			)
	
	RETURN SCOPE_IDENTITY() 
END






















-- EDITAR
IF EXISTS (SELECT * FROM SYS.objects WHERE OBJECT_ID = OBJECT_ID(N'SP_EDITAR_CARRO'))
	DROP PROCEDURE SP_EDITAR_CARRO
GO
CREATE PROCEDURE SP_EDITAR_CARRO
	@ID			INT,
	@MARCA		VARCHAR(50),		
	@MODELO		VARCHAR(50),	
	@COR		VARCHAR(50),		
	@ANO		DATE,		
	@PRECO		MONEY
AS
BEGIN
	UPDATE tb_CARRO SET 
						CAR_MARCA = @MARCA,	
						CAR_MODELO = @MODELO,	
						CAR_COR = @COR,		
						CAR_ANO = @ANO,		
						CAR_PRECO = @PRECO	
							
	WHERE CAR_CODIGO = @ID
						
END		
EXEC SP_EDITAR_CARRO 4, 'Volkswagen', 'Gol G5', 'Branco', '2016', '23500'















-- DELETAR
IF EXISTS (SELECT * FROM SYS.objects WHERE OBJECT_ID = OBJECT_ID(N'SP_DELETAR_CARRO'))
	DROP PROCEDURE SP_DELETAR_CARRO
GO
CREATE PROCEDURE SP_DELETAR_CARRO
	@ID		INT
AS
BEGIN 
	
	DELETE tb_CARRO WHERE CAR_CODIGO = @ID

END

EXEC SP_DELETAR_CARRO 31


BEGIN TRAN
ROLLBACK


















-- SELECIONAR CARRO
IF EXISTS (SELECT * FROM SYS.objects WHERE OBJECT_ID = OBJECT_ID(N'SP_PROCURAR_CARRO'))
	DROP PROCEDURE SP_PROCURAR_CARRO
GO
CREATE PROCEDURE SP_PROCURAR_CARRO
	@MARCA		VARCHAR(100) = NULL,
	@MODELO		VARCHAR(100) = NULL,
	@COR		VARCHAR(100) = NULL,
	@ANO		DATE		 = NULL,
	@PRECO		VARCHAR(100) = NULL,
	@DESCRICAO  VARCHAR(100) = NULL
AS
BEGIN 
	
	SELECT  CAR_MARCA 'MARCA',
			CAR_MODELO 'MODELO',
			CAR_COR 'COR',
			CAR_ANO 'ANO',
			CAR_PRECO 'PREÇO',

			OPC_DESCRICAO 'ACESSORIOS',
	
			FK_CAR_CODIGO,
			FK_OPC_CODIGO

		FROM tb_CARRO CAR
			INNER JOIN tb_OPCIONAL_CARRO OC
				ON CAR.CAR_CODIGO = OC.FK_CAR_CODIGO
			INNER JOIN tb_OPCIONAL OPC
				ON OC.FK_OPC_CODIGO = OPC.OPC_CODIGO
		
			WHERE 
					   CAR.CAR_MARCA LIKE '%' + @MARCA + '%'
					OR (@MODELO IS NULL OR (CAR.CAR_MODELO = '%' + @MODELO + '%'))
					OR (@COR IS NULL OR (CAR.CAR_COR = '%' + @COR + '%'))
					OR (@ANO IS NULL OR (CAR.CAR_ANO = '%' + (convert(varchar(4),year(@ANO))) + '%'))
					OR (@PRECO IS NULL OR (CAR.CAR_PRECO = '%' + @PRECO + '%'))
					OR (@DESCRICAO IS NULL OR (OPC.OPC_DESCRICAO = '%' + @DESCRICAO + '%'))
END

EXEC SP_PROCURAR_CARRO 











-- BUSCAR CARRO
IF EXISTS (SELECT * FROM SYS.objects WHERE OBJECT_ID = OBJECT_ID(N'SP_BUSCAR_CARRO'))
	DROP PROCEDURE SP_BUSCAR_CARRO
GO
CREATE PROCEDURE SP_BUSCAR_CARRO
	@ID		INT
AS
BEGIN 
	SELECT  CAR_MARCA 'MARCA',
			CAR_MODELO 'MODELO',
			CAR_COR 'COR',
			CAR_ANO 'ANO',
			CAR_PRECO 'PREÇO',

			OPC_DESCRICAO 'ACESSORIOS',
	
			FK_CAR_CODIGO,
			FK_OPC_CODIGO

		FROM tb_CARRO CAR
			INNER JOIN tb_OPCIONAL_CARRO OC
				ON CAR.CAR_CODIGO = OC.FK_CAR_CODIGO
			INNER JOIN tb_OPCIONAL OPC
				ON OC.FK_OPC_CODIGO = OPC.OPC_CODIGO
		
			WHERE CAR.CAR_CODIGO = @ID
END 

EXEC SP_BUSCAR_CARRO 50






/*
			{
				"marca":"Fiat",
				"modelo":"Uno 1.4",
				"cor":"Vermelho",
				"ano":"2016",
				"preco":"32490",
	
				"opcionais":[
								{"opcional":7},
								{"opcional":8},
								{"opcional":12}
						   ]
	
			}
*/